### ISSUE TITLE
Text search documents

### ISSUE THREAD

**Issue by SteveECda** [mikeckennedy/python-jumpstart-course-demos#31]
Hi Mike. 
I didn't find the target documents for app 8 of the Jump-start course. I couldn't match your results because I don't have the .txt documents you searched. 

Could you make those available? 

Thanks
Steve Erickson
ps. I love your podcast & have bought the 2016 bundle. This course is bringing back old memories and new ambitions.

**Comment by mikeckennedy** [comment]
Hi Steve,

Thanks for taking the courses and listening to the podcast!

I don't have the text files available. I didn't put them in github because
it was 2GB of text. All I did was download maybe 10 long books in text form
from https://www.gutenberg.org/ Then I duplicated them (copy paste, repeat)
until I had a ton of text to mess with.

Best,
Michael

**Comment by dneff** [comment]
A simple python project resolved this for me:

https://github.com/puntonim/gutenberg-bulk-downloader

I downloaded a few thousand txt files, unzipped them and had 1.2 GB worth of text pretty quickly.

**Comment by mikeckennedy** [comment]
Thanks for the link @dneff that is handy.
