### ISSUE TITLE
'Override method in object' and others... Wizard Battle (7)

### ISSUE THREAD

**Issue by AUGuise** [mikeckennedy/python-jumpstart-course-demos#39]
As I have been working through the tutorial for the Wizard battle, I am finding, relatively early on, that there are a number of overrides that are cause the app to fail. 

![image](https://user-images.githubusercontent.com/39177296/40954839-0de9ba14-684c-11e8-9938-e0aac813758b.png)

I have tried retyping the code and finally resigned to copy/paste of your code with the same result.

**Comment by mikeckennedy** [comment]
Hi @AUGuise,

The overrides are intentional but they do not cause the app / game to fail. It's working fine for me. Here is exactly what I typed in running on Python 3.6 just now:

![screen shot 2018-06-04 at 9 13 47 pm](https://user-images.githubusercontent.com/2035561/40955000-4a1cc04a-683c-11e8-8fe6-1c2cf0f5bb52.png)

Do you have more details about the error and problem? I don't see errors in your screenshot above.

Best,
Michael

**Comment by AUGuise** [comment]
I found the issue. I only copied the part of the code that I believed was in error which was why it seemed like there was something else going on. Feeling pretty silly. 

Thanks for the quick response. These tutorials have been great btw!

**Comment by mikeckennedy** [comment]
No worries. Glad you're all set and enjoying the courses! :)  Thanks.
