### ISSUE TITLE
Want to add more instructions for creating Python virtualenv in Windows.  

### ISSUE THREAD

**Issue by xzackaly** [mikeckennedy/python-jumpstart-course-demos#44]
Hi, Mike.

I hit a speed bump trying to set up python virtual environment on Windows, but figured it out through G-search (Google).    

I am asking permission to do a PR to update the document “venv_on_windows.md”.

1.	The “Scripts\activate” in the tutorial DOES work in Windows, without needing “.bat”. The key to getting the Windows shell to work as desired is to do a one-time change to some default shell script settings.  Until I made the script settings change, I was unsuccessful at getting activate or activate.bat to work.

2.	The “where” command  is “where.exe” (where.exe virtualenv).  

3.	And finally, I would like to add the shell command format for creating a virtual environment for earlier versions of Python, pre-Python3.3.    
 
Thanks for your consideration.  

@xzackaly

**Comment by 1oglop1** [comment]
Hi @xzackaly Do not ask persmission to create PR, but rather create it with suggested changes :)
Checkout the link below for detailed information.
https://help.github.com/en/articles/creating-a-pull-request

**Comment by mikeckennedy** [comment]
Hi guys. Definitely go ahead and do the PR. @1oglop1 I agree, no need to ask permission in general. Sometimes I'm a little touching about *improvements* because I value having the code match the video recording more than having perfect code so don't want to waste people's time. That said, a markdown doc to help folks on Windows is definitely welcomed.

**Comment by xzackaly** [comment]
Thanks, Mike. : )

**Comment by mikeckennedy** [comment]
Thank you!
